# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Relational Data Embeddings
# email: 
description: >- # this means to ignore newlines until "baseurl:"
  KEN: Relational Data Embeddings for Feature Enrichment with Background Information 
baseurl: "ken_embeddings" # the subpath of your site, e.g. /blog
url: "soda-inria.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  soda-inria
repository: soda-inria/ken_embeddings

## Comment out the github right now, because people think that it is the
## github of the code of KEN
#github:
#  is_project_page: true
#  repository_url: https://github.com/soda-inria/ken_embeddings
#  owner_name: soda-inria
#  owner_url: https://github.com/soda-inria

papers:
  - name: Preprint paper
    url: https://hal.archives-ouvertes.fr/hal-03848124/


# Build settings
markdown: kramdown
theme: jekyll-theme-cayman

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
